# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamasemedia', '0006_auto_20160517_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapagerelatedlink',
            name='caption',
            field=models.CharField(help_text=b'Image Caption', max_length=255, null=True),
        ),
    ]
