# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mamasemedia', '0007_auto_20160517_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaindexpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mediapage',
            name='name',
        ),
    ]
