# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0008_auto_20160106_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='slides',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name=b'Slides of Lectures'),
        ),
    ]
