# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0010_coursecategorypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategorypage',
            name='name',
        ),
    ]
