# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0011_remove_coursecategorypage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledgeplatform.CourseCategoryPage'),
        ),
    ]
