# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20151113_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='reading',
            field=models.CharField(blank=True, default=b'0.0', max_length=50, null=True),
        ),
    ]
