# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20160517_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='sreading',
            field=models.CharField(blank=True, default=b'0.0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='reading',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
