# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20160524_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[(b'WEATHER_STATION', b'Weather Station'), (b'RIVER_DEPTH', b'River Depth'), (b'RAINFALL_TEMP', b'Rainfall and Temp'), (b'DEPTH_TEMP', b'River Depth and Temp')], default=b'Weather Station', max_length=50),
        ),
    ]
