# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[(b'WEATHER_STATION', b'Weather Station'), (b'RIVER_DEPTH', b'River Depth'), (b'RAIN_TEMP', b'Rainfall and Temp'), (b'DEPTH_RAIN', b'River Depth and Rainfall')], default=b'Weather Station', max_length=50),
        ),
    ]
