# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20160531_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='river',
            field=models.CharField(blank=True, choices=[(b'MARA', b'Mara'), (b'AMALA', b'Amala'), (b'TALEK', b'Talek'), (b'NYANGORES', b'Nyangores')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[(b'WEATHER_STATION', b'Weather Station'), (b'RIVER_DEPTH', b'River Depth'), (b'RAIN_TEMP', b'Rainfall and Temp'), (b'DEPTH_RAIN', b'River Depth and Rainfall')], default=b'WEATHER_STATION', max_length=50),
        ),
    ]
