# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_remove_channel_river'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='river',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rivers', to='utils.River'),
        ),
    ]
