# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_channel_river'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
