# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20160914_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelfield',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelfields', to='utils.Channel'),
        ),
    ]
