# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryApp',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageApp',
        ),
    ]
